name = "contextlinc"
compatibility_date = "2024-01-15"
pages_build_output_dir = "out"

[env.production]
routes = [
  { pattern = "context.thefadil.site/*", custom_domain = true }
]

[env.production.vars]
ENVIRONMENT = "production"
APP_URL = "https://context.thefadil.site"

[env.preview]
routes = [
  { pattern = "contextlinc-preview.pages.dev/*" }
]

[env.preview.vars]
ENVIRONMENT = "preview"
APP_URL = "https://contextlinc-preview.pages.dev"